# Generated by Django 4.2.21 on 2026-03-18 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piggy_banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiggyBankMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('piggy_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='piggy_banks.piggybank')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
