# Generated by Django 4.2.21 on 2026-03-26 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("piggy_banks", "0002_piggybankmovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="piggybank",
            name="cdi_percentage",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name="piggybank",
            name="last_cdi_accrual_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]

